name: Build

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  build-lint-test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack and install Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --immutable
      - run: yarn build

      - name: Cache snap build
        if: ${{ matrix.node-version == '22.x' }}
        uses: actions/cache@v4
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}

  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
